name: flutterproject1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.0.2
  logger: ^2.4.0
  flutter_card_scanner: ^1.0.4
  permission_handler: ^11.3.1
  mobile_scanner: ^2.0.0
  google_ml_kit: ^0.7.0
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0+2
  camera_process: ^1.0.1
  webview_flutter: ^4.9.0
  flutter_svg: ^1.0.3
  fl_chart: ^0.40.0
  barcode: ^2.1.0
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_web: ^0.2.3
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.15.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/kakao_map.html
    - lib/src/assets/btn_map.svg
    - lib/src/assets/btn_return.svg
    - lib/src/assets/btn_search.svg
    - lib/src/assets/Coffee.svg
    - lib/src/assets/Rectangle 21.png
    - lib/src/assets/Rectangle 23.png
    - lib/src/assets/Rectangle 24.png
    - lib/src/assets/Rectangle 7.png
    - lib/src/assets/barcode.png
    - lib/src/assets/barcode2.png
    - lib/src/assets/barcode3.png
    - lib/src/assets/barcode4.png
    - lib/src/assets/barcode5.png
